const homeStatus = [
  "SRV_AUTH",
  "SRV_USER_SEND",
  "SRV_USER_FILE",
  "SRV_USER_AUDIO",
  "SRV_USER_IMAGE",
  "SRV_GROUP_DEL",
  "SRV_GROUP_JOIN",
  "SRV_GROUP_SEND",
  "SRV_GROUP_FILE",
  "SRV_GROUP_IMAGE",
  "SRV_GROUP_AUDIO",
  "SRV_CONTACT_CARD",
  "SRV_CHAT_PIN",
  "SRV_EDIT_CONTACT",
  "SRV_GROUP_ADD_MANAGER_HISTORY",
  "SRV_GROUP_CHANGE_ADMIN_HISTORY",
  "SRV_GROUP_REMOVE_MANAGER_HISTORY",
  "SRV_CALL_HISTORY", // 播出通話
  "SRV_CALL_CANCEL_HISTORY", // 語音通話取消訊息
  "SRV_CALL_NO_RESPONSE_HISTORY", // 通話無回應訊息
  "SRV_VIDEO_HISTORY", // 播出視訊通話
  "SRV_VIDEO_CANCEL_HISTORY", // 視訊通話取消訊息
  "SRV_GROUP_CALL_HISTORY", // 群組播出通話
  "SRV_GROUP_CALL_FINISH_HISTORY", // 群組結束通話
  "SRV_GROUP_VIDEO_HISTORY", // 群組播出視訊通話
  "SRV_GROUP_VIDEO_FINISH_HISTORY", // 群組結束視訊通話
]

      
export default homeStatus
